### ISSUE TITLE
Реализовать функцию generate

### ISSUE THREAD

**Issue by sholokhova** [sholokhova/sort_generation#1]

**Comment by dronnikovigor** [comment]
Не очень понятна суть задания. 
Мы создаём пустой массив. Насколько я понимаю, его элементы должны быть заданы исходя из правил: 
> Один из возможных способов реализации generate:
> - Начинаем с нуля, на каждом шаге, если rand()%100 + 1 > repetitions_percent,
> то прибавляем единицу, иначе - ноль
> - Ожидаемый интервал чисел [0, (100-repetitions_percent)/100 * len]
> - В массив сразу записываем отображение на отрезок [min_val, max_val] 
> (при этом может нарушиться repetitions_percent)

Тогда становится не понятно, для чего необходимо первое условие. Так же при попытке создать интервал из второго условия - получается ошибка деления на ноль. И так же не очень понятно, что за отрезок [min_val, max_val].

**Comment by sholokhova** [comment]
Имелось в виду как-то так:
arr[i] = arr[i-1] +(rand()%100 + 1 > repetitions_percent ? 1 : 0) % (max_val - min_val) + min_val;

Начинаем заполнять с элемента с индексом 1

**Comment by sholokhova** [comment]
Отрезок [min_val, max_val] определен в задании к лабораторным работам. В принципе можно и не отображать на этот интервал, для порядка + можно отслеживать переполнение

**Comment by dronnikovigor** [comment]
При таком варианте реализации опять же получается ошибка деления на ноль
`arr[i] = (arr[i-1] +(rand()%100 + 1 > repetitions_percent ? 1 : 0)) * ((max_val - min_val) / ((100-repetitions_percent)/100 * len)) + min_val;`

А такой вариант генерируется: 
`arr[i] = arr[i-1] +(rand()%100 + 1 > repetitions_percent ? 1 : 0) % (max_val - min_val) + min_val;`

**Comment by sholokhova** [comment]
arr[i] = (arr[i-1] +(rand()%100 + 1 > repetitions_percent ? 1 : 0)) * ((max_val - min_val) / ((100-repetitions_percent)/100 * len)) + min_val;

Тут ошибка. Наверно за два прохода придется.
Сначала заполняем массив числами в интервале [0..(100-repetitions_percent)/100 * len]. А затем переводим в интервал [min_val, max_val]. (иначе мы прибавляем единицу к уже отображеннуму значению)

**Comment by sholokhova** [comment]
(100-repetitions_percent)/100 * len - тут проблема целочисленного деления, можно например
(100-repetitions_percent)/100.0 * len или явным приведением к вещественному типу

**Comment by sholokhova** [comment]
> Наверно за два прохода придется.

А можно в отдельной переменной хранить предыдущее неотображенное число

**Comment by sholokhova** [comment]
То есть мы генерируем последовательность чисел, начиная с 0. На каждом шаге мы или повторяем предыдущее число (с вероятностью repetitions_percent) или переходим к следующему (соответственно с вероятностью 100 - repetitions_percent). Затем отображаем полученную последовательность на отрезок [min_val, max_val]. Так мы заранее можем примерно подсчитать максимальное число, которое получим - (100-repetitions_percent)/100 * len, то можем выполнять отображение сразу при заполнении

**Comment by dronnikovigor** [comment]
'((max_val - min_val) / ((100-repetitions_percent)/100 * len)) + min_val;
'
Если я правильно понимаю, то из этого должен появится коэффициент отображения на отрезок?

**Comment by dronnikovigor** [comment]
Пришлось сделать три цикла. В первом цикле производится задание чисел из отрезка [0..(100-repetitions_percent)/100 * len]. Во втором отображение на отрезок [0, max_val]. Т.к. при задании используется предыдущее число, сразу и генерировать и отображать за один подход не получится. И в третьем цикле к отображённому числу прибавляется нижняя граница min_val. 
Возможно можно и поизящнее сделать...
