### ISSUE TITLE
Расширить функцию sort

### ISSUE THREAD

**Issue by sholokhova** [sholokhova/sort_generation#5]
Добавить передачу функции сравнения как аргумента в функцию sort

**Comment by Axiino** [comment]
У меня вопрос. Мне нужно написать функцию, которая будет сравнивать два элемента массива и , если, например, элемент a[i]< a[j], то функция будет выдавать 0, иначе 1. Я правильно понял?

**Comment by sholokhova** [comment]
Добавить аргумент в функцию sort аналогично Compare comp в
http://www.cplusplus.com/reference/algorithm/sort/
